// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EditorService 编辑器/终端管理,绑定给前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddManualEditor 手动添加编辑器或终端。
 */
export function AddManualEditor(name: string, command: string, args: string, kind: $models.EditorKind): $CancellablePromise<$models.Editor> {
    return $Call.ByID(2556268784, name, command, args, kind);
}

/**
 * DeleteEditor 按 ID 删除。
 */
export function DeleteEditor(id: string): $CancellablePromise<void> {
    return $Call.ByID(3897795078, id);
}

/**
 * ListEditors 返回全部编辑器/终端。
 */
export function ListEditors(): $CancellablePromise<$models.Editor[] | null> {
    return $Call.ByID(2935507518);
}

/**
 * ReorderEditors 按给定 ID 顺序重排编辑器列表(拖拽排序落盘);ids 必须恰好覆盖全部现有 ID。
 */
export function ReorderEditors(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(676049759, ids);
}

/**
 * ScanEditors 全量重扫:保留 manual;同名 ID 保留 Enabled/Args 人工改动;消失的 scan 项删除。
 * 扫描在锁外进行(文件系统慢,不阻塞其他存储调用),合并落盘才持锁。
 */
export function ScanEditors(): $CancellablePromise<$models.Editor[] | null> {
    return $Call.ByID(4206968005);
}

/**
 * SetDefaultEditor 设默认编辑器;"" 清除;需已存在。
 */
export function SetDefaultEditor(id: string): $CancellablePromise<void> {
    return $Call.ByID(4143364808, id);
}

/**
 * SetDefaultTerminal 设默认终端;"" 清除;需已存在。
 */
export function SetDefaultTerminal(id: string): $CancellablePromise<void> {
    return $Call.ByID(2907183681, id);
}

/**
 * UpdateEditor 按 ID 全量更新(Icon 留空则沿用旧值)。
 */
export function UpdateEditor(editor: $models.Editor): $CancellablePromise<$models.Editor> {
    return $Call.ByID(2929140108, editor);
}
