// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Editor 编辑器/终端条目。
 */
export interface Editor {
    /**
     * 稳定 slug: vscode/zed/konsole/...;手动的 "m-"+8位hex
     */
    "id": string;
    "name": string;

    /**
     * 前端图标 slug
     */
    "icon": string;

    /**
     * PATH 中的可执行名或绝对路径;可含空格(flatpak Exec 整行)
     */
    "command": string;

    /**
     * 参数模板,含 {path} 占位符,空格分隔,默认 "{path}"
     */
    "args": string;
    "kind": EditorKind;

    /**
     * "scan" | "manual"
     */
    "source": string;
    "enabled": boolean;

    /**
     * true=终端内编辑器(nvim/vim/hx),启动时包一层终端
     */
    "inTerminal": boolean;
}

/**
 * EditorKind 编辑器类别:"editor" | "terminal" | "cli"。
 */
export enum EditorKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindEditor = "editor",
    KindTerminal = "terminal",

    /**
     * CLI 编码工具(codex/claude/grok…):终端里在项目目录直接执行
     */
    KindCLI = "cli",
};

/**
 * Project 项目条目。
 */
export interface Project {
    "id": string;
    "name": string;
    "note": string;
    "path": string;
    "isTemp": boolean;

    /**
     * unix 毫秒
     */
    "createdAt": number;

    /**
     * unix 毫秒,0=从未打开
     */
    "lastOpenedAt": number;
    "openCount": number;
}

/**
 * Settings 应用设置。
 */
export interface Settings {
    /**
     * 新项目默认父目录
     */
    "defaultPath": string;

    /**
     * ""=未设置
     */
    "defaultEditorId": string;

    /**
     * ""=未设置
     */
    "defaultTerminalId": string;
}
