// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService 项目管理,绑定给前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddProject 登记已存在目录;name 为空取 basename。
 */
export function AddProject(path: string, name: string, note: string): $CancellablePromise<$models.Project> {
    return $Call.ByID(1525935144, path, name, note);
}

/**
 * CreateProject 创建新项目目录;parentPath 为空用 Settings.DefaultPath。
 */
export function CreateProject(name: string, note: string, parentPath: string): $CancellablePromise<$models.Project> {
    return $Call.ByID(3794430337, name, note, parentPath);
}

/**
 * CreateTempProject 在 <DefaultPath>/tmp 下建临时项目;name 为空自动生成,绝不自动删除。
 */
export function CreateTempProject(name: string, note: string): $CancellablePromise<$models.Project> {
    return $Call.ByID(2475209739, name, note);
}

/**
 * DeleteProject 删除项目;deleteFiles 为 true 时同时删除磁盘上的项目目录。
 * 护栏:根目录与用户主目录绝不删除;磁盘删除失败时报错并保留列表项。
 */
export function DeleteProject(id: string, deleteFiles: boolean): $CancellablePromise<void> {
    return $Call.ByID(1959829424, id, deleteFiles);
}

/**
 * ListProjects 返回全部项目(按创建顺序)。
 */
export function ListProjects(): $CancellablePromise<$models.Project[] | null> {
    return $Call.ByID(1083075410);
}

/**
 * OpenProject 用编辑器或终端打开项目;成功才更新 LastOpenedAt/OpenCount。
 */
export function OpenProject(id: string, editorID: string): $CancellablePromise<void> {
    return $Call.ByID(3378515093, id, editorID);
}

/**
 * UpdateProject 按 ID 全量更新 Name/Note/Path,统计字段沿用存量。
 */
export function UpdateProject(project: $models.Project): $CancellablePromise<$models.Project> {
    return $Call.ByID(755684514, project);
}
