// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 应用设置,绑定给前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSettings 读设置;未初始化时返回零值。
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3034808949);
}

/**
 * PickDirectory 原生目录选择框;取消返回 "", nil。
 */
export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(4083973240);
}

/**
 * SaveSettings 保存设置;DefaultPath 不存在则 MkdirAll。
 */
export function SaveSettings(settings: $models.Settings): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2662658340, settings);
}
